apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender-app
  labels:
    app: sender-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sender-app
  template:
    metadata:
      labels:
        app: sender-app
    spec:
      containers:
      - name: sender-app
        image: bsexercisecontainerregistry.azurecr.io/sender-app:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8007
---
apiVersion: v1
kind: Service
metadata:
  name: sender-app
spec:
  selector: 
    app: sender-app
  type: ClusterIP
  ports:
  - port: 8007
    targetPort: 8007
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver-app
  labels:
    app: receiver-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receiver-app
  template:
    metadata:
      labels:
        app: receiver-app
    spec:
      containers:
      - name: receiver-app
        image: bsexercisecontainerregistry.azurecr.io/receiver-app:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8008
---
apiVersion: v1
kind: Service
metadata:
  name: receiver-app
spec:
  selector: 
    app: receiver-app
  type: ClusterIP
  ports:
  - port: 8008
    targetPort: 8008
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
  labels:
    app: redis-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-app
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
      - name: redis-app
        image: bsexercisecontainerregistry.azurecr.io/redis-app:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8009
---
apiVersion: v1
kind: Service
metadata:
  name: redis-app
spec:
  selector: 
    app: redis-app
  type: ClusterIP
  ports:
  - port: 8009
    targetPort: 8009