apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender
  labels:
    app: sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
    spec:
      containers:
      - name: sender
        image: sender
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: sender
spec:
  selector: 
    app: sender
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver
  labels:
    app: receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receiver
  template:
    metadata:
      labels:
        app: receiver
    spec:
      containers:
      - name: receiver
        image: receiver
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: receiver
spec:
  selector: 
    app: receiver
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: askred
  labels:
    app: askred
spec:
  replicas: 1
  selector:
    matchLabels:
      app: askred
  template:
    metadata:
      labels:
        app: askred
    spec:
      containers:
      - name: askred
        image: askred
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: askred
spec:
  selector: 
    app: askred
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80