FROM python:3.10.4

COPY sender.py config.yml requirements.txt ./
RUN mkdir -p /File_to_post
COPY ./file_to_post/data.json /file_to_post/data.json

RUN pip install -r requirements.txt

CMD [ "python", "./sender.py" ]