FROM python:3.10.4

RUN groupadd -r application && useradd -r -g application application && mkdir -p /application_dir && chown application /application_dir
WORKDIR /application_dir

COPY sender.py config.yml requirements.txt ./
RUN mkdir -p ./file_to_post
COPY ./file_to_post/ ./file_to_post/

RUN pip install -r requirements.txt

USER application
CMD [ "python", "./sender.py" ]