name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.4
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.4"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install pyyaml
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test app 1
      working-directory: .\app1_sender
      run: |
        pytest
    - name: Test app 2
      working-directory: .\app2_receiver
      run: |
        pytest
    - name: Test app 3
      working-directory: .\app3_redis
      run: |
        pytest
